<?php
return [
    // General / Titles
    'title' => '💊ဆေးဆိုင်ငယ်များအတွက် ပစ္စည်းစာရင်းစီမံခန့်ခွဲမှု',
    'welcome' => 'ကြိုဆိုပါတယ်၊',
    'logout' => 'ထွက်ခွာရန်',
    'dashboard_title' => 'မင်္ဂလာပါ Dashboard',
    'dashboard_subtitle' => 'အဓိက လုပ်ဆောင်ချက်များကို ဒီနေရာမှ ဝင်ရောက်နိုင်သည်။',

    // Navbar / Menu
    'medicine_list' => 'ဆေးပစ္စည်း စာရင်း',
    'goods_receipt' => 'ကုန်လက်ခံမှု',
    'sales' => 'ရောင်းချမှု',
    'reports' => 'အစီရင်ခံစာများ',
    'suppliers' => 'ပေးသွင်းသူများ',
    'reorder_alerts' => 'ပြန်မှာရန် သတိပေးချက်များ',
    'expiry_alerts' => 'သက်တမ်းကုန် သတိပေးချက်များ',
    'nav_medicines' => 'ဆေးများ',
    'nav_goods_receipt' => 'ကုန်လက်ခံမှု',
    'nav_sales' => 'ရောင်းချမှု',
    'nav_reports' => 'အစီရင်ခံစာများ',
    'nav_sales_report' => 'ရောင်းချမှု အစီရင်ခံစာ',
    'nav_low_stock_report' => 'စတော့လျော့နည်းမှု အစီရင်ခံစာ',
    'nav_waste_report' => 'ပစ်ပယ်မှု အစီရင်ခံစာ',
    'nav_reorder_alerts' => 'ပြန်မှာရန် သတိပေးချက်',
    'nav_expiry_alerts' => 'သက်တမ်းကုန် သတိပေးချက်',
    'nav_suppliers' => 'ပေးသွင်းသူများ',

    // Dashboard Cards / Sections
    'goods_receipt_title' => 'ကုန်လက်ခံမှု',
    'goods_receipt_desc' => 'ရရှိထားသော ဆေးပစ္စည်းများကို မှတ်တမ်းတင်ပြီး စတော့ကို ပြင်ဆင်ပါ။',
    'goods_receipt_btn' => 'မှတ်တမ်းတင်ရန်',

    'suppliers_title' => 'ပေးသွင်းသူများ',
    'suppliers_desc' => 'သင်၏ ဆေးပစ္စည်းပေးသွင်းသူများကို စီမံခန့်ခွဲပါ။',
    'suppliers_btn' => 'ပေးသွင်းသူများ စီမံခန့်ခွဲရန်',

    'reorder_title' => 'ပြန်မှာရန် သတိပေးချက်များ',
    'reorder_desc' => 'ပြန်မှာယူရန် လိုအပ်သော ဆေးများကို စောင့်ကြည့်ပါ။',
    'reorder_btn' => 'သတိပေးချက်များကြည့်ရန်',

    'expiry_title' => 'သက်တမ်းကုန် သတိပေးချက်များ',
    'expiry_desc' => 'သက်တမ်းနီးစပ် သို့မဟုတ် သက်တမ်းကုန်သော ဆေးများကို စစ်ဆေးပါ။',
    'expiry_btn' => 'သက်တမ်းကုန် သတိပေးချက်',

    // Medicine Management
    'manage_medicines_title' => 'ဆေး စီမံခန့်ခွဲမှု',
    'manage_medicines_desc' => 'ဆေးများ ထည့်သွင်း၊ ပြင်ဆင်၊ ဖျက်သိမ်းပါ',
    'manage_medicines_btn' => 'ဆေးများ စီမံခန့်ခွဲရန်',
    'add_medicine' => 'ဆေးအသစ် ထည့်ရန်',
    'medicine_list_title' => 'ဆေးစာရင်း',

    'brand_name' => 'အမှတ်တံဆိပ်အမည်',
    'generic_name' => 'ထုတ်ကုန်အမည်',
    'barcode' => 'ဘားကုဒ်',
    'type' => 'အမျိုးအစား',
    'dosage' => 'ဆေးပမာဏ',
    'dosage_form' => 'သောက်သုံးပုံစံ',
    'category' => 'အမျိုးအစား',
    'quantity' => 'အရေအတွက်',
    'unit' => 'ယူနစ်',
    'lot_number' => 'လော့နံပါတ်',
    'mfg_date' => 'ထုတ်လုပ်သည့်ရက်',
    'expiry_date' => 'သက်တမ်းကုန်ရက်',
    'cost_price' => 'ကုန်ကျစရိတ်',
    'selling_price' => 'အရောင်းဈေး',
    'min_reorder' => 'နိမ့်ဆုံးမှာယူပမာဏ',
    'reorder_level' => 'ပြန်မှာရန် အဆင့်',
    'contact_person' => 'ဆက်သွယ်ရန် ပုဂ္ဂိုလ်',

    'actions' => 'လုပ်ဆောင်ချက်များ',
    'edit' => 'ပြင်ဆင်ရန်',
    'delete' => 'ဖျက်ရန်',
    'confirm_delete' => 'ဤအချက်အလက်ကို ဖျက်မည်မှာ သေချာပါသလား?',    

    // Sales and Purchase
    'sales_title' => 'ရောင်းချမှု / ဝယ်ယူမှု မှတ်တမ်း',
    'sales_desc' => 'ရောင်းချမှု၊ ဝယ်ယူမှုနှင့် စတော့လျော့နည်းမှုများကို စောင့်ကြည့်ပါ',
    'sales_btn' => 'ရောင်းချမှု စီမံခန့်ခွဲရန်',
    'select_medicine' => 'ဆေးရွေးရန်',
    'lot_number_select' => 'လော့နံပါတ် ရွေးရန်',
    'selling_price_label' => 'အရောင်းဈေး (ကျပ်)',
    'quantity_label' => 'အရေအတွက်',
    'discount_percent' => 'လျှော့စျေး (%)',
    'total_amount' => 'စုစုပေါင်း (ကျပ်)',
    'payment_method' => 'ငွေပေးချေမှု နည်းလမ်း',
    'cash' => 'ငွေသား',
    'kbz_pay' => 'KBZ Pay',
    'wave_money' => 'Wave Money',
    'record_sale_btn' => 'ရောင်းချမှု မှတ်တမ်းတင်ရန်',

    // Disposal / Wastage
    'disposal_title' => 'ပျက်စီး/ဆုံးရှုံးမှု မှတ်တမ်း',
    'waste_reason' => 'အကြောင်းရင်း',
    'waste_quantity' => 'ပျက်စီးသော အရေအတွက်',
    'waste_cart_empty' => 'ပစ္စည်းမရှိပါ',
    'goods_receipt' => 'ကုန်အဝင်စာရင်း',
'supplier' => 'ကုန်ပေးသူ',
'medicine_name' => 'ဆေးအမည်',
'lot_number' => 'လော့နံပါတ်',
'mfg_date' => 'ထုတ်လုပ်သည့်နေ့',
'expiry_date' => 'သက်တမ်းကုန်ချိန်',
'quantity' => 'အရေအတွက်',
'purchase_price' => 'ဝယ်ဈေး',
'selling_price' => 'အရောင်းဈေး',
'save' => 'သိမ်းမည်',
'reset' => 'ပြန်လည်သတ်မှတ်ရန်',
'add_medicine' => 'ဆေးအသစ်ထည့်ရန်',
    'name' => 'ဆေးအမည်',
    'barcode' => 'ဘားကုဒ်',
    'category' => 'အမျိုးအစား',
    'type' => 'ပုံစံ (Tablet, Syrup...)',
    'dosage' => 'ပမာဏ',
    'manufacturer' => 'ထုတ်လုပ်သူ',
    'lot_number' => 'Lot နံပါတ်',
    'expiry_date' => 'သက်တမ်းကုန်ရက်',
    'manufacturing_date' => 'ထုတ်လုပ်သည့်နေ့',
    'purchase_price' => 'ဝယ်ဈေး',
    'selling_price' => 'ရောင်းဈေး',
    'quantity' => 'အရေအတွက်',
    'supplier' => 'ပေးသွင်းသူ',
    'upload_photo' => 'ဓာတ်ပုံတင်ရန်',

    // Buttons
    'save' => 'သိမ်းဆည်းရန်',
    'reset' => 'အလုံးစုံ ဖျက်ရန်',
    'search' => 'ရှာရန်',
    'search_placeholder' => 'အမည်၊ ဘားကုဒ်၊ အမျိုးအစား၊ Lot... ဖြင့်ရှာရန်',

    // Alerts
    'error_expiry' => 'သက်တမ်းကုန်ရက်သည် ယနေ့ထက်နောက်ပိုင်း ဖြစ်ရမည်။',
    'success_save' => 'အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။',
    'error_required' => 'လိုအပ်သောအချက်အလက်များ ဖြည့်ပေးပါ။',


    // Reports
    'reports_title' => 'အစီရင်ခံစာများ',
    'daily_sales' => 'နေ့စဉ်ရောင်းအား',
    'weekly_sales' => 'တပတ်ရောင်းအား',
    'monthly_sales' => 'လစဉ်ရောင်းအား',
    'yearly_sales' => 'နှစ်စဉ်ရောင်းအား',
    'stock_report' => 'စတော့အစီရင်ခံစာ',
    'expiry_report' => 'သက်တမ်းကုန်အစီရင်ခံစာ',
    'low_stock_report' => 'စတော့နည်းခြင်းအစီရင်ခံစာ',
    'waste_report' => 'ပျက်စီးဆုံးရှုံးမှုအစီရင်ခံစာ',
    'reorder_report' => 'ပြန်မှာရန် အစီရင်ခံစာ',

    'export_excel' => 'Excel အဖြစ် ထုတ်ယူရန်',
    'export_pdf' => 'PDF အဖြစ် ထုတ်ယူရန်',

    'top_selling_medicines' => 'အရောင်းအများဆုံး ဆေးများ',
    'total_revenue' => 'စုစုပေါင်းဝင်ငွေ',
    'total_profit' => 'စုစုပေါင်းအမြတ်',

    // Buttons and form actions
    'save' => 'သိမ်းဆည်းရန်',
    'cancel' => 'မလုပ်ဆောင်ပါ',
    'search' => 'ရှာဖွေရန်',
    'filter' => 'စစ်ထုတ်ရန်',
    'add_new' => 'အသစ်ထည့်ရန်',
    'update' => 'ပြင်ဆင်ရန်',
    'close' => 'ပိတ်ရန်',
    'submit' => 'တင်သွင်းရန်',

    // Validation messages
    'required_field' => 'ဤအကွက်ကို ဖြည့်သွင်းရန် လိုအပ်ပါသည်။',
    'invalid_input' => 'အချက်အလက် မမှန်ကန်ပါ။',
    'min_length' => 'အနည်းဆုံး အရှည်မှာ :min စာလုံး ဖြစ်ရမည်။',
    'max_length' => 'အများဆုံး အရှည်မှာ :max စာလုံး ဖြစ်ရမည်။',

    // Misc
    'no_records_found' => 'မှတ်တမ်းမတွေ့ပါ',
    'loading' => 'ဖတ်ရှုနေပါသည်...',
    'confirm_action' => 'ဤလုပ်ဆောင်ချက်ကို သေချာပါသလား။',
    'success_save' => 'မှတ်တမ်း သိမ်းဆည်းပြီးပါပြီ။',
    'success_delete' => 'မှတ်တမ်း ဖျက်ပြီးပါပြီ။',
    'error_occurred' => 'အမှားတစ်ခု ဖြစ်ပွားခဲ့သည်။ ထပ်မံကြိုးစားပါ။',
        'selling_price' => 'အရောင်းဈေး',
    'reset' => 'ပြန်လည်သတ်မှတ်ရန်',
    'search_placeholder' => 'နာမည်၊ ဘားကုဒ်၊ အမျိုးအစား၊ လော့နံပါတ်ဖြင့်ရှာရန်...',
    'goods_receipt_title' => 'ကုန်ဝယ်လက်ခံစာ',
    'supplier' => 'ပေးသွင်းသူ',
    'select_supplier' => '— ပေးသွင်းသူ ရွေးချယ်ပါ —',
    'supplier_hint' => 'ကုန်အဝယ်စာကို ပေးသွင်းသူနှင့် ချိတ်ဆက်ထားနိုင်သည်။',
    'medicine' => 'ဆေးပစ္စည်း',
    'medicine_placeholder' => 'အမည် သို့မဟုတ် ဘားကုဒ် ရိုက်ပါ…',
    'medicine_hint' => 'စာရင်းထဲမှ ရွေးချယ်ပါ (ID ဖြင့် ချိတ်ဆက်မည်)။',
    'barcode' => 'ဘားကုဒ်',
    'barcode_placeholder' => 'မထည့်ပါလျှင် Generate နှိပ်ပါ',
    'generate' => 'Generate လုပ်မည်',
    'barcode_hint' => 'ဘားကုဒ်မရှိပါက အလိုအလျောက် Generate လုပ်နိုင်သည်။',
    'lot_number' => 'Lot နံပါတ်',
    'mfg_date' => 'ထုတ်လုပ်သည့်နေ့',
    'expiry_date' => 'သက်တမ်းကုန်နေ့',
    'purchase_price' => 'ဝယ်ဈေး (Ks)',
    'selling_price' => 'ရောင်းဈေး (Ks)',
    'selling_price_hint' => 'လက်ရှိ ရောင်းဈေး သတ်မှတ်နိုင်ပါသည်။',
    'quantity' => 'အရေအတွက်',
    'save' => 'သိမ်းဆည်းမည်',
    'reset' => 'ပြန်ချိန်မည်',

    // Errors
    'error_select_medicine' => 'စာရင်းထဲမှ သက်ဆိုင်သော ဆေးပစ္စည်းကို ရွေးချယ်ပါ။',
    'error_expiry_past' => 'သက်တမ်းကုန်နေ့သည် ယနေ့ထက် နောက်ကျရမည်။',
    'error_mfg_after_exp' => 'ထုတ်လုပ်သည့်နေ့သည် သက်တမ်းကုန်နေ့ထက် နောက်မကျရပါ။',



    // Footer
    'footer' => 'ဆေးဆိုင်ငယ်များအတွက် ပစ္စည်းစာရင်းစီမံခန့်ခွဲမှု',
];
